### ISSUE TITLE
Dataset available?

### ISSUE THREAD

**Issue by dsellanes** [albertkx/Berkeley-Crossword-Solver#6]
Hello, in the paper you mention: 

_"we publicly release our code, models, and dataset:"_

Is the dataset in the repo? 

Thank you!

**Comment by priyamtejaswin** [comment]
+1
The README also refers to a `data` folder multiple times. But no data seems to have been shared.

**Comment by Eric-Wallace** [comment]
Hey, just added the link in the readme. The dataset has been available through Huggingface datasets here https://huggingface.co/datasets/albertxu/CrosswordQA
