### ISSUE TITLE
Crossword sample

### ISSUE THREAD

**Issue by SiqiKe** [albertkx/Berkeley-Crossword-Solver#7]
Would you please release one or two formated crosswords first if the whole dataset isn't ready right away? I tried to use your Crossword.py on .json file found on xwordinfo.com but failed. The initialize_grids didn't match the grids' format on .json.

**Comment by Eric-Wallace** [comment]
Hey I added an example of an NYT puzzle inside the solver folder. You can also downloads any `.puz` file from various websites online and use those as input.
